### ISSUE TITLE
Actividad 1: Infografia

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-1-infografia-FedericoVictorianoSierra#2]
[Infografía (Federico Victoriano Sierra (5US)).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-FedericoVictorianoSierra/files/9440601/Infografia.Federico.Victoriano.Sierra.5US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Infografía (Federico Victoriano Sierra (5US)).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-FedericoVictorianoSierra/files/9440601/Infografia.Federico.Victoriano.Sierra.5US.pdf)

**Comment by abicoronel** [comment]
calificaión: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
